type: rtdetrv2
name: comic_text_bubble_v4s-r20250626
provider: ogkalu
display_name: Comic-Text-Bubble-v4s
model_path: D:/Ddown/comic-text-and-bubble-detector/detector-v4-s_int8.onnx
input_height: 640
input_width: 640
conf_threshold: 0.5
classes:
  - bubble
  - text_bubble
  - text_free
